version: '3'


services:
  python:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: prod_erybj_service
    container_name: prod_erybjp_service
    ports:
      - "6851:6851"
    command: uwsgi --ini uwsgi.ini
  redis:
    image: redis:latest
    container_name: prod_erybjp_redis
    ports:
      - "6379:6379"
    networks:
      service:
        aliases:
          - redis

  chrome:
    restart: always
    image: selenium/standalone-chrome-debug:latest
    container_name: prod_erybjp_chrome
    ports:
      - "4444:4444"
      - "5904:5900"
    depends_on:
      - python
    shm_size: 2g

networks:
  service:
