version: '3'


services:
  python:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: prod_erybj_service
    container_name: prod_erybjp_service
    network_mode: bridge
    volumes:
      - /home/yuanbaojun/app/erybjp/data/:/usr/src/app/erybjp/uiplatform/utils/data/
    ports:
      - "6851:6851"
    command: uwsgi --ini uwsgi.ini
  selenoid:
    restart: always
    network_mode: bridge
    image: aerokube/selenoid:latest
    container_name: prod_erybjp_selenoid
    ports:
      - "4444:4444"
    depends_on:
      - python
    shm_size: 2g
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/yuanbaojun/app/erybjp/erybjp-master:/etc/selenoid/
      - /home/yuanbaojun/app/erybjp/erybjp-master/logs/:/opt/selenoid/logs/
      - /etc/localtime:/etc/localtime
    command: -limit 10 -service-startup-timeout 1m -enable-file-upload -log-output-dir /opt/selenoid/logs
  selenoid-ui:
    image: "aerokube/selenoid-ui"
    network_mode: bridge
    restart: always
    container_name: prod_erybjp_selenoid-ui
    environment:
      - TZ=Asia/Shanghai
    links:
      - selenoid
    ports:
      - "5901:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]
networks:
  service: