version: '3'


services:
  python:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: prod_erybj_service
    container_name: prod_erybjp_service
    ports:
      - "6851:6851"
    command: python manage.py runserver -p 6851
  redis:
    image: redis:latest
    container_name: prod_erybjp_redis
    ports:
      - "6379:6379"
    networks:
      service:
        aliases:
          - redis
  selenium-hub:
    restart: always
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    volumes:
      - /opt/conf/:/mnt
      - /etc/localtime:/etc/localtime
    environment:
      - TZ=Asia/Shanghai
      - GRID_MAX_SESSION=10

  chrome:
    restart: always
    image: selenium/node-chrome-debug:latest
    container_name: prod_erybjp_chrome
    ports:
      - "5901:5901"
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
      - START_XVFB=false
      - TZ=Asia/Shanghai

  firefox:
    image: selenium/node-firefox-debug:latest
    container_name: prod_erybjp_firefox
    volumes:
      - /dev/shm:/dev/shm
      - /etc/localtime:/etc/localtime
    ports:
      - "5902:5902"
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5
      - START_XVFB=false
      - TZ=Asia/Shanghai

networks:
  service:
