version: '3'


services:
  python:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: prod_erybj_service
    container_name: prod_erybjp_service
    ports:
      - "6851:6851"
    command: uwsgi --ini uwsgi.ini
  redis:
    image: redis:latest
    container_name: prod_erybjp_redis
    ports:
      - "6379:6379"
    networks:
      service:
        aliases:
          - redis
  hub:
    restart: always
    image: registry.aliyuncs.com/denverdino/selenium-hub
    container_name: prod_erybjp_hub
    ports:
      - "4444:4444"
    volumes:
      - /opt/conf/:/mnt
    
  chrome:
    restart: always
    image: registry.aliyuncs.com/denverdino/selenium-node-chrome
    container_name: prod_erybjp_chrome
    ports:
      - "5901:5901"
    links:
      - hub
    labels:
      aliyun.scale: "3"
  firefox:
    image: registry.aliyuncs.com/denverdino/selenium-node-firefox
    container_name: prod_erybjp_firefox
    ports:
      - "5902:5902"
    links:
      - hub
    labels:
      aliyun.scale: "3"
networks:
  service:
