version: '3'

services:
  python:
    restart: always
    build:
      context: .
      dockerfile: ./Dockerfile
    image: prod_monkey_service
    container_name: prod_monkey_service
    ports:
      - "6851:6851"
    command: gunicorn --bind 0.0.0.0:8000 monkey.wsgi:application
  redis:
    image: redis:latest
    container_name: prod_erybjp_redis
    ports:
      - "6379:6379"
    networks:
      service:
        aliases:
          - redis

  chrome:
    image: selenium/standalone-chrome:latest
    container_name: prod_erybjp_chrome
    ports:
      - "4444:4444"
    depends_on:
      - python
    networks:
      - service

networks:
  service:
